#include "always.h"
#include "language/language.h"

#ifdef __ANDROID__
char const * Android_Fetch_String(int id)
{
    switch (id) {
        case TXT_NONE: return " ";
        case TXT_COPYRIGHT: return "© 2000 Electronic Arts, All Rights Reserved";
        case TXT_TIME_FORMAT_HOURS: return "Time:%02d:%02d:%02d";
        case TXT_TIME_FORMAT_NO_HOURS: return "Time:%02d:%02d";
        case TXT_MONEY_FORMAT_1: return "$%d";
        case TXT_MONEY_FORMAT_2: return "%s ($%d)";
        case TXT_READY: return "Ready";
        case TXT_HOLD: return "On Hold";
        case TXT_PRIMARY: return "Primary";
        case TXT_PRI: return "Pri.";
        case TXT_OK: return "OK";
        case TXT_YES: return "Yes";
        case TXT_NO: return "No";
        case TXT_SCENARIO_WON: return "Mission Accomplished";
        case TXT_SCENARIO_LOST: return "Mission Failed";
        case TXT_CANCEL: return "Cancel";
        case TXT_IGNORE: return "Ignore";
        case TXT_CLICK_CONTINUE: return "Click to Continue";
        case TXT_MISSION_EFFICIENCY: return "MISSION EFFICIENCY";
        case TXT_MISSION_TIME_LAPSE: return "MISSION TIME LAPSE";
        case TXT_CURRENCY: return "CURRENCY";
        case TXT_CASUALTIES: return "CASUALTIES";
        case TXT_BEST_SCORES: return "Best Scores";
        case TXT_STRUCTURES: return "Structures";
        case TXT_RESUME_MISSION: return "Resume Mission";
        case TXT_VIDEO: return "Video";
        case TXT_MORE: return "-- More --";
        case TXT_INTERFACE: return "Interface";
        case TXT_TEAM: return "Team";
        case TXT_SELECTION: return "Selection";
        case TXT_CONTROL: return "Control";
        case TXT_CREATE_TEAM: return "Create Team %2d";
        case TXT_CD_ERROR1: return "Tiberian Sun is unable to detect your CD ROM drive.";
        case TXT_DLL_INVALID: return "Tiberian Sun requires %s version %d.%d or newer.\n\nPlease consult the read me for instructions on how to\nobtain a newer version of %s.";
        case TXT_ENEMY_SOLDIER: return "Enemy Soldier";
        case TXT_ENEMY_VEHICLE: return "Enemy Unit";
        case TXT_ENEMY_STRUCTURE: return "Enemy Structure";
        case TXT_INITGAME_FAILED: return "Failed to initialize. Please reinstall.";
        case TXT_PREPARECOM_FAILED: return "One or more DLL files were missing\nor damaged. Please reinstall.";
        case TXT_NO_SOUND_CARD: return "No Sound Card Detected";
        case TXT_INVALIDMODE: return "This product requires a 16bit pixel depth!";
        case TXT_LOST: return "Game Over";
        case TXT_MOUSE_REQUIRED: return "A mouse is required for playing Tiberian Sun.";
        case TXT_DSOUND_ACCESS: return "Unable to play Direct Sound primary buffer.";
        case TXT_DDRAW_UNKNOWN: return "Unrecognized Direct Draw result code.";
        case TXT_VIDEO_ERROR: return "Error - Unable to set the video mode.";
        case TXT_SHORT_TITLE: return "Tiberian Sun";
        case TXT_CRITICALLY_LOW: return "Warning - you are critically low on free disk space for saving games. Do you want to play Tiberian Sun anyway?";
        case TXT_TAB_SIDEBAR: return "Sidebar";
        case TXT_TAB_BUTTON_CONTROLS: return "Options";
        case TXT_SHADOW: return "Unrevealed Terrain";
        case TXT_OPTIONS_MENU: return "Options Menu";
        case TXT_STOP: return "Stop";
        case TXT_DEPLOY_OBJECT: return "Deploy Object";
        case TXT_DEPLOY_OBJECT_DESC: return "Deploy selected object(s).";
        case TXT_WAYPOINTMODE: return "Waypoint Mode";
        case TXT_WAYPOINTMODE_DESC: return "Toggle waypoint placement mode on / off.";
        case TXT_ON: return "On";
        case TXT_OFF: return "Off";
        case TXT_MULTIPLAYER_GAME: return "Multiplayer Game";
        case TXT_SCRNCAP: return "Screen Capture";
        case TXT_SCRNCAP_DESC: return "Take a snapshot of the game screen. (Saved as 'SCRNxxxx.PCX' file in Tiberian Sun run directory.)";
        case TXT_SENDING_GO: return "Sending GO request - Please Wait...";
        case TXT_WAITING_GO: return "Waiting for GO response - Please Wait...";
        case TXT_SENDING_GO_ACK: return "Sending GO acknowlegement - Please Wait...";
        case TXT_CWAIT_STAR70: return "*70";
        case TXT_CWAIT_70NUM: return "70#";
        case TXT_CWAIT_1170: return "1170";
        case TXT_EASY: return "Easy";
        case TXT_NORMAL: return "Normal";
        case TXT_HARD: return "Hard";
        case TXT_HIGH: return "High";
        case TXT_LOW: return "Low";
        case TXT_FASTEST: return "Fastest";
        case TXT_FASTER: return "Faster";
        case TXT_SLOWER: return "Slower";
        case TXT_SLOWEST: return "Slowest";
        case TXT_SLOW: return "Slow";
        case TXT_MEDIUM: return "Medium";
        case TXT_FAST: return "Fast";
        case TXT_UNABLE_READ_SCENARIO: return "Unable to read scenario!";
        case TXT_ERROR_LOADING_GAME: return "Error loading game!";
        case TXT_OBSOLETE_SAVEGAME: return "[OBSOLETE]";
        case TXT_MUSTENTER_DESCRIPTION: return "You must enter a description!";
        case TXT_ERROR_SAVING_GAME: return "Error saving mission!";
        case TXT_DELETE_FILE_QUERY: return "Delete this file?";
        case TXT_EMPTY_SLOT: return "[EMPTY SLOT]";
        case TXT_MAP: return "Map: %s";
        case TXT_EXPANSION_TITLE: return "Firestorm";
        case TXT_REQUEST_DENIED: return "Request denied.";
        case TXT_UNABLE_PLAY_WAAUGH: return "Unable to play; scenario not found.";
        case TXT_NOTHING_TO_JOIN: return "Nothing to join!";
        case TXT_NAME_ERROR: return "You must enter a name!";
        case TXT_YOURGAME_OUTDATED: return "Your game version is outdated.";
        case TXT_DESTGAME_OUTDATED: return "Destination game version is outdated.";
        case TXT_THATGUYS_GAME: return "%s's Game";
        case TXT_THATGUYS_GAME_BRACKET: return "[%s's Game]";
        case TXT_REJECT: return "Reject";
        case TXT_CANT_REJECT_SELF: return "You can't reject yourself!";
        case TXT_SELECT_PLAYER_REJECT: return "You must select a player to reject.";
        case TXT_CREDITS_COLON: return "Credits:";
        case TXT_ONLY_ONE: return "Only one player?";
        case TXT_OOPS: return "Oops!";
        case TXT_TO: return "To %s:";
        case TXT_TO_ALL: return "To All:";
        case TXT_MESSAGE: return "Message:";
        case TXT_CONNECTION_LOST: return "Connection to %s lost!";
        case TXT_LEFT_GAME: return "%s has left the game.";
        case TXT_PLAYER_DEFEATED: return "%s has been defeated!";
        case TXT_COMPUTER: return "Computer";
        case TXT_NONAME: return "[NONAME]";
        case TXT_DEFAULT: return "Default";
        case TXT_SETTINGS: return "Settings";
        case TXT_NAME_COLON: return "Name:";
        case TXT_OUT_OF_SYNC: return "The game is out of sync.";
        case TXT_PACKET_TOO_LATE: return "Packet received too late!";
        case TXT_USER_SIGNED_OFF: return "User signed off!";
        case TXT_POWER_DRAIN: return "Power = %d\rDrain = %d";
        case TXT_STAND_BY: return "Please Stand By...";
        case TXT_LOW_POWER: return "Low Power";
        case TXT_KILLS_COLON: return "Kills:";
        case TXT_SPY_INFO: return "Spy Info";
        case TXT_INFANTRY: return "Infantry";
        case TXT_BUILDNGS: return "Buildings";
        case TXT_CIVILIAN_BUILDING: return "Civilian Building";
        case TXT_TECHNICIAN: return "Technician";
        case TXT_UNITS: return "Units";
        case TXT_TO_REPLAY: return "Would you like to replay this mission?";
        case TXT_SURRENDER: return "Surrender";
        case TXT_GAMENAME_MUSTBE_UNIQUE: return "Your game name must be unique.";
        case TXT_GAME_IS_CLOSED: return "Game is closed.";
        case TXT_NAME_MUSTBE_UNIQUE: return "Your name must be unique.";
        case TXT_RECONNECTING_TO: return "Connection to %s has been interrupted. Attempting to reconnect.";
        case TXT_WAITING_FOR_CONNECTIONS: return "Waiting for all players to enter the game....";
        case TXT_TIME_ALLOWED: return "Time allowed: %02d seconds";
        case TXT_JUST_YOU_AND_ME: return "From Computer: It's just you and me now!";
        case TXT_HAS_ALLIED: return "%s has allied with %s";
        case TXT_AT_WAR: return "%s declares war on %s";
        case TXT_SCENARIOS_DO_NOT_MATCH: return "Scenarios don't match.";
        case TXT_CONTINUE: return "Continue";
        case TXT_QUEUE_FULL: return "Data Queue Overflow";
        case TXT_SPECIAL_WARNING: return "%s changed game options!";
        case TXT_WAITING_FOR_OPPONENT: return "Waiting for Opponent";
        case TXT_GAME_WAS_SAVED: return "Mission Saved";
        case TXT_SPACE_CANT_SAVE: return "Insufficient disk space to save a game.  Please delete a previous saved games to free up some disk space and try again.";
        case TXT_LOADING: return "Mission is loading. Please wait...";
        case TXT_LOBBY: return "Lobby";
        case TXT_SAVING_GAME: return "Mission saving - Please Wait...";
        case TXT_GAME_FULL: return "Game is full.";
        case TXT_MUST_SELECT_GAME: return "You must select a game!";
        case TXT_S_PLAYING_S: return "%s playing %s";
        case TXT_ONLY_HOST_CAN_MODIFY: return "Only the host can modify this option.";
        case TXT_GAME_CANCELLED: return "Game was cancelled.";
        case TXT_S_FORMED_NEW_GAME: return "%s has formed a new game.";
        case TXT_GAME_NOW_IN_PROGRESS: return "%s's game is now in progress.";
        case TXT_NO_DIAL_TONE: return "No dial tone. Ensure your modem is connected to the phone line and try again.";
        case TXT_CONNECTING: return "Connecting...";
        case TXT_SELECT_SETTINGS: return "Please select 'Settings' to setup default configuration";
        case TXT_ANSWERING: return "Answering...";
        case TXT_INITIALIZING_MODEM: return "Initializing Modem...Standby";
        case TXT_ERROR_NO_INIT: return "Error - Modem did not respond to initialisation string.";
        case TXT_ERROR_NO_DISABLE: return "Error - Unable to disable modem auto answer.";
        case TXT_ERROR_TOO_MANY: return "Error - Too many errors initialising modem - Aborting.";
        case TXT_ERROR_ERROR: return "Error - Modem returned error status.";
        case TXT_ERROR_TIMEOUT: return "Error - TIme out waiting for connect.";
        case TXT_RECEIVING_SCENARIO: return "Receiving scenario from host.";
        case TXT_SENDING_SCENARIO: return "Sending scenario to remote players.";
        case TXT_NO_FLOW_CONTROL_RESPONSE: return "Error - Modem failed to respond to flow control command. Your Windows configuration may be incorrect.";
        case TXT_NO_COMP_DISABLE_RESPONSE: return "Error - Modem failed to respond to compression disable command. Your Windows configuration may be incorrect.";
        case TXT_NO_EC_DISABLE_RESPONSE: return "Error - Modem failed to respond to error correction disable command. Your Windows configuration may be incorrect.";
        case TXT_UNABLE_TO_OPEN_PORT: return "Invalid Port or Port is in use";
        case TXT_INVALID_PORT_ADDRESS: return "Invalid Port/Address. COM 1-4 OR ADDRESS";
        case TXT_IRQ_ALREADY_IN_USE: return "IRQ already in use";
        case TXT_ERROR_IN_INITSTRING: return "Error in the InitString";
        case TXT_MODEM_OR_LOOPBACK: return "Not a Null Modem Cable Attached! It is a modem or loopback cable.";
        case TXT_UNABLE_FIND_MODEM: return "Unable to find modem. Check power and cables.";
        case TXT_NULL_CONNERR_CHECK_CABLES: return "Connection error! Check your cables. Attempting to Reconnect...";
        case TXT_MODEM_CONNERR_REDIALING: return "Connection error! Redialing...";
        case TXT_MODEM_CONNERR_WAITING: return "Connection error! Waiting for Call...";
        case TXT_WAITING_CONNECT: return "Waiting to Connect...";
        case TXT_CUSTOM: return "CUSTOM -";
        case TXT_COM1: return "COM1 - 3F8";
        case TXT_COM2: return "COM2 - 2F8";
        case TXT_COM3: return "COM3 - 3E8";
        case TXT_COM4: return "COM4 - 2E8";
        case TXT_NO_CARRIER: return "No carrier.";
        case TXT_NUCLEAR_BOMB: return "Atom Bomb";
        case TXT_ION_CANNON: return "Ion Cannon";
        case TXT_FIRESTORM: return "Firestorm Defense Toggle";
        case TXT_ION_STORM_APPROACHING: return "Warning: Ion Storm approaching.";
        case TXT_ION_STORM: return "Warning: Ion Storm here!";
        case TXT_EM_PULSE: return "EM Pulse";
        case TXT_FIRESTORM_ON: return "Activated";
        case TXT_CHARGING: return "Charging...";
        case TXT_YELLOW: return "Yellow";
        case TXT_GRAY: return "Gray";
        case TXT_RED: return "Red";
        case TXT_PURPLE: return "Purple";
        case TXT_BLUE: return "Blue";
        case TXT_CYAN: return "Cyan";
        case TXT_TAN: return "Tan";
        case TXT_GREEN: return "Green";
        case TXT_MODE: return "Mode";
        case TXT_RANK: return "Rank";
        case TXT_BACK: return "Back";
        case TXT_NOT_IN_LADDER: return "Sorry, that player or rank is not in the ladder.";
        case TXT_BYTES_W_TIME: return "Bytes read: %d / %d.    Time left: %d seconds";
        case TXT_BYTES_WO_TIME: return "Bytes read: %d / %d.";
        case TXT_FINDING_PATCH: return "Finding Patch...";
        case TXT_NO_SERV_LIST: return "Couldn't get the server list";
        case TXT_UPGRADEREQUIRED: return "An upgrade is required for this game\nDo you want to download it now?\n \n \nWarning: use of \"trainers\", third-party cheat programs, or any other modification of Tiberian Sun may cause the automatic update procedure to fail. Please remove any such programs or reinstall Tiberian Sun before continuing.";
        case TXT_DOWNLOADING_X_OF_Y: return "Downloading file %d of %d...";
        case TXT_SERVER_ERROR: return "Chat Server Error";
        case TXT_LOGIN_USED: return "That login is already being used.";
        case TXT_BADPASS: return "That login or password was incorrect.";
        case TXT_BANNED: return "You've been temporarily banned. Would you like to open your web browser to get more information?";
        case TXT_CANT_CONNECT: return "Could not connect to Westwood Online, check your Internet connection.";
        case TXT_CHANCREATE_FAILED: return "Could not create the channel";
        case TXT_CREATED_CHAN: return "Created channel: %s";
        case TXT_CANT_JOINCHAN: return "Error joining channel %X";
        case TXT_PAGESENT: return "Page was successful.";
        case TXT_PAGEDISABLED: return "User has pages disabled";
        case TXT_PAGEUSERGONE: return "User isn't logged in";
        case TXT_PAGEFAILED: return "Couldn't page user";
        case TXT_FINDOK: return "User is in channel %s";
        case TXT_FINDNONE: return "User isn't in any channels";
        case TXT_FINDGONE: return "User isn't logged in";
        case TXT_FINDDISABLED: return "User has find disabled";
        case TXT_FINDFAILED: return "Find failed";
        case TXT_YOURE_DISCON: return "You've been disconnected from the server";
        case TXT_BANNEDTILL: return "You've been banned from Westwood Online until %s";
        case TXT_CHAN_BAN: return "%s has been banned from the channel";
        case TXT_CHAN_UNBAN: return "The channel ban on %s has been removed";
        case TXT_YOURE_KICKED: return "You were kicked out of channel %s by %s";
        case TXT_USER_KICKED: return "User %s was kicked out of channel %s by %s";
        case TXT_YOULEFT: return "You left channel %s";
        case TXT_FETCHING_SERVLIST: return "Fetching server list";
        case TXT_CONNECTING_SERVER: return "Connecting to Westwood Online";
        case TXT_REQ_CHANLIST: return "Requesting channel list";
        case TXT_JOINLOB: return "Joining Lobby";
        case TXT_JOININGCHAN: return "Joining channel: %s";
        case TXT_SEARCHING: return "SEARCHING...";
        case TXT_SEARCHING_FOR: return "Searching for %s....";
        case TXT_ACCEPTFIRST: return "All users must accept before the game can start.";
        case TXT_NO_BOUND_NET_CARD: return "IPX not available";
        case TXT_INVALID_SOCKET: return "Socket number must be between 0 and 16383";
        case TXT_DESTNET_ADDR_ERROR: return "Destination network address must be in the format xx.xx.xx.xx";
        case TXT_ABOUT_TO_TRY_MODE: return "The display mode will be changed. If there is a problem with the new display mode then wait and the old mode will be restored.";
        case TXT_APIMISSING: return "The Westwood online support library is either missing or invalid. Please reinstall the shared internet components from your CD.";
        case TXT_APIWRONGVERSION: return "The installed version of the Westwood Online support library is too old. Please reinstall the shared internet components from your CD.";
        case TXT_NOTCHANOP: return "You must be a channel operator to do this.";
        case TXT_NOSQUAD: return "You are not in a Tiberian Sun squad.";
        case TXT_LAUNCHBROWSER: return "Would you like to launch your web browser to visit this page?";
        case TXT_NOBROWSER: return "You don't have a web browser associated with HTML files.";
        case TXT_BAD_CHANNAME: return "You can't make a channel with this name.  Try removing spaces and other punctuation.";
        case TXT_BAD_CHANKEY: return "You can't make a channel with this password. Try removing spaces and other punctuation.";
        case TXT_CANTCREATE_CHAN: return "You cannot create this channel.";
        case TXT_NAME_BLANK: return "Your player name is blank, please enter a name.";
        case TXT_GAME_CLOSED: return "That game channel has closed";
        case TXT_CHANNEL_FULL: return "That channel is full";
        case TXT_JOINBAN: return "You've been banned from this channel";
        case TXT_ENTER_MESSAGE: return "Please enter a message to send";
        case TXT_NOT_IN_CHAN: return "You can't send a message when you're not in a channel";
        case TXT_WOL_CONNLOST: return "Lost connection to Westwood Online, outside users will not be able to page you.";
        case TXT_DSOUND_PROCEED: return "Proceeding with audio disabled.";
        case TXT_REQ_NICK: return "Requesting new login...";
        case TXT_DISK_NAME: return "Tiberian Sun Disk %d";
        case TXT_CONFIRM_SAVE: return "Overwrite existing save game?";
        case TXT_DISKFULL: return "Warning - you are critically low on free disk space for saving games.";
        case TXT_SIGNING_OFF: return "Signing off - Please Wait...";
        case TXT_CD_DIALOG_1: return "Please insert a Tiberian Sun CD into the CD-ROM drive.";
        case TXT_CD_DIALOG_2: return "Please insert CD %d (%s) into the CD-ROM drive.";
        case TXT_NAMES: return "Players";
        case TXT_LOSSES: return "Losses";
        case TXT_ECONOMY: return "Economy";
        case TXT_SCORE: return "Score";
        case TXT_KILLS: return "Kills";
        case TXT_RESET_HOTKEYS: return "Are you sure you want to reset the hotkey assignments?";
        case TXT_DSOUND_CANT_CREATE: return "Warning - Unable to create Direct Sound Object.";
        case TXT_DSOUND_NO_COOP: return "Warning - Unable to set Direct Sound cooperative level.";
        case TXT_DSOUND_NO_PRIMARY: return "Warning - Unable to create Direct Sound primary buffer.";
        case TXT_DSOUND_INCOMPAT: return "Warning - Your sound card does not meet the product's audio requirements.";
        case TXT_GDI01A: return "Destroy all enemy units";
        case TXT_GDI02A: return "The Nod forces that attacked our Phoenix base are in this sector.  Their base must be destroyed in order to secure the region.  However, there is a significant civilian population requiring evacuation.  GDI transports will evacuate the civilians once all Nod SAM sites are destroyed.  The Nod base can then be safely terminated.";
        case TXT_GDI03A: return "It is highly probable that the Brotherhood will attempt to remove technology from the crash site and store it at the technology center.  Locate and secure the crash site, then capture the technology center.";
        case TXT_GDI03B: return "Destroying the base in this sector will prevent further removal of artifacts from the crash site.  In addition, Nod will not be able to reinforce the site from this location.";
        case TXT_GDI04A: return "Be advised, the Brotherhood will attempt to destroy the impact site.  GDI reinforcements are en route.  Protect the site until they arrive.";
        case TXT_GDI05A: return "A sensor net protects the valley where Tratos is being held.  To facilitate his rescue, we must disable the array that controls this highly sensitive net.  Once down, it will be much easier to get Tratos out of the valley.";
        case TXT_GDI05C: return "Tratos is being held in a hospital prison facility within this sector.  Avoid detection and rescue Tratos from the facility.  Once he is out, a transport will be sent in to evacuate him.  Once Tratos is clear, destroy all Nod forces in the area to prevent further experimentation.";
        case TXT_GDI06A: return "The large dams that power Vega's base lie in this sector.  Destroying them will temporarily drain power from his base.  To aid you in your objective, attack his island facility before he can bring new generators online.  The dam can be destroyed by disabling the two regulator stations in this sector.  GDI air support will be available if you can find a way to contact them and confirm your target. ";
        case TXT_GDI06B: return "Vega's base is secreted on an island in this sector.  Reaching it will be difficult, as there is only one overland access.  Your best chance of success lies in the use of amphibious APCs to land on the island and penetrate Vega's defenses.  Once on the island, destroy Vega's facility and command center.";
        case TXT_GDI07A: return "Nod has taken over much of our Hammerfest base in their search for the disrupter. Nod has reactivated the perimeter to prevent GDI from attacking.  Water assault remains your only option.  Find the Firestorm Defense structure generating the perimeter and deactivate it.  Only then can reinforcements arrive.  Proceed to destroy Nod's primary base, and prevent them from attacking again.";
        case TXT_GDI08A: return "It is imperative that you prevent the train from reaching the Nod base.  Remember, destroying the locomotive will immediately stop the train.  Recent ice melts in the region have disabled the only train bridge.  You must move quickly as Nod engineers are on their way to repair it.  The crystals can be recovered easily if you get to the train before Nod can repair the bridge.  Otherwise, we will need to attack the base in order to reclaim the crystals.";
        case TXT_GDI09A: return "The mutants are being held on an island in this sector.  We can spare a small force to attempt a rescue.  The area leading to the island is heavily guarded.  If you are detected, more Nod forces will arrive.  Avoiding Nod patrols is advised.  You must rescue all ten mutants and lead them to the dust-off zone.  Periodic airstrikes will be available.";
        case TXT_GDI09B: return "Destroying the supply base here will prevent the missile complex from receiving reinforcements.";
        case TXT_GDI09C: return "The train transporting the mutants is headed to this power grid.  The grid powers the missile complex.  Merely destroying the grid is inadequate: Nod will compensate by building more power plants at the base.  Use all the mutants to plant C4 charges on all the power plants.  We'll detonate the C4 when we attack the missile complex.";
        case TXT_GDI09D: return "Complete destruction of the missile complex is essential.  Be advised, Nod will use their Tiberium missiles and their new fighter prototypes against you.";
        case TXT_GDI10A: return "One of two possible locations for the fighter production facility.  Use the mutants to locate its whereabouts while remaining undetected.  If detected, Nod will cloak the factory and deploy more troops.  Hide the mutants, and Nod will once again uncloak their base.  After the base location is recorded, GDI dropships will immediately arrive with reinforcements.";
        case TXT_GDI10B: return "Another possible location of the fighter production facility.  Use the mutants to locate the position of the fighter production facility.  They must remain undetected. If Nod suspects enemy forces, they will cloak their production facility and deploy troops.  If the mutants can hide from the Nod troops for a short period, Nod will assume the area is clear, and uncloak the base.  Once we have recorded the location of the base, the mission will be complete.";
        case TXT_GDI11A: return "Be advised: Kane is determined to destroy you.  The ion storm has grounded the Kodiak.  We must protect it until the storm abates.  Production will be limited.  There is a high probability of equipment malfunction.  Caution is advised.";
        case TXT_GDI12A: return "Impulse signatures emanating from Cairo suggest Kane will launch his world-altering missile within hours.  You must destroy the pyramid temple before he has the chance to launch.  There are no alternatives.";
        case TXT_NOD01A: return "Destroy all enemy units.";
        case TXT_NOD02A: return "Hassan communicates to the Brotherhood through a nearby TV station.  With the Brotherhood in chaos, the opportunity to divide Hassan from his followers presents itself.  Capture the TV station and those once loyal to Kane's technology of peace will return to the fold.  And as for Hassan's pathetic guards -- crush them.";
        case TXT_NOD03A: return "The infidel Hassan has been tracked to this region of Cairo.  Build a base and remove the usurper.";
        case TXT_NOD03B: return "We have become aware of an imprisoned commander in this region who WAS loyal to Hassan.  Free him and his forces and they should be sympathetic to our cause -- and help in the capture of Hassan.  The commander may have information vital to my.......your movement.";
        case TXT_NOD04A: return "Taking out this weak GDI position will allow us to reclaim our Sarajevo temple without interruption.  Move to an open area and build your base.  GDI patrols are known to be in the area.  Do not mar the brotherhood's name any further.";
        case TXT_NOD05A: return "The alien craft is located in this region - find it!  You must utilize your stealth advantage, as the area is infested with GDI.  Once the craft is located, get an engineer inside to retrieve the Tacitus.  Should you encounter Vega's forces, consider them expendable.";
        case TXT_NOD06A: return "Control of the mutants is in our grasp.  Their headquarters is located to the north of your drop-off position.  The GDI units you will need to implicate in this deception occupy a small base to the southwest.  Do not mar the Brotherhood's name any further.  Allow the blame to fall squarely on Solomon's shoulders.";
        case TXT_NOD06B: return "You must reach the medical colony in the region without being prematurely detected by GDI and forcing a base evacuation.  To prevent this, consider first destroying the 3 sensor towers protecting the base.  Our new artillery unit should be sufficient for the job, even in your hands.  Once inside the base, the capture of the mutant female should be simple.";
        case TXT_NOD06C: return "The mutant female may be trying to reach the underground railway system located in New Detroit.  Move in and control the station before she arrives.  If she boards the train, you must stop it immediately.  This may be our last chance of capturing the abomination.";
        case TXT_NOD07A: return "The informant must make contact with the mutants south of the GDI base.  Use the mutants to protect the informant and to eliminate GDI patrols.  Reinforcements will arrive after you have secured the railway tunnel here.  Use them to locate and destroy the research facility.  The mutants, of course, are expendable.";
        case TXT_NOD07B: return "Use the cyborg commando and his team to locate the bio-toxin tanker trucks.  Both trucks must reach the convoy point here if they are to arrive in time to aid you in your assault against the research facility.  GDI patrols are known to be in the area.";
        case TXT_NOD08A: return "A cyborg commando has been sent to retrieve you.  Once free, rendezvous with your rescue team to the south.  Use them to locate and free Oxanna before she is transported to the main GDI facility.  After she has been freed, capture a GDI transport to make your escape.  ";
        case TXT_NOD09A: return "In this sector lies a Nod base overrun with tiberium-based lifeforms.  Find the base, reactivate it, and use the tiberium life to fill our missiles.  When you have enough of the tiberium substance, launch the missile against the GDI base and destroy it.";
        case TXT_NOD09B: return "Enter the sector and deploy your base.  Once you have established a tiberium waste facility, convoys of tiberium waste will begin arriving.  Protect the convoys at all cost.  Once we have enough tiberium waste, the missile will be ready for use against GDI.  Destroying their base, once it is infected, will be a simple matter.";
        case TXT_NOD10A: return "We must destroy GDI's new weapon.  They will, of course, build more in the future but it will buy us valuable time.  We know GDI is testing the Mammoth somewhere in this sector.  Use a chameleon spy to infiltrate a GDI comm center and locate the test site.  Your fighter prototype should be all you need to obliterate the nuisance.";
        case TXT_NOD11A: return "The GDI defense perimeter is located here.  Do not destroy any GDI factories during your assault - you will need them to build GDI units under our control.  Once Jake McNeil's inspection detail is in our converted base, attack!  Kill all but McNeil.  Use the special toxin soldiers provided to control McNeil.  Once he has been \"persuaded\" to help us in our cause, EVAC him as directed.  If he detects the trap, capture him before he can flee the sector.   ";
        case TXT_NOD12A: return "Kane's vision is at hand.  Unfortunately GDI's orbital station, the Philadelphia, can stop the missile that will take us into the future.   We must destroy the Philadelphia at all costs!  The Philadelphia will require three orbits over this sector before it can locate our missile.  You must get three ICBM launchers into position before the Philadelphia's final orbit is complete.  With the ICBMs in place, we can bring GDI's command station down.  All this remains contingent, of course, on McNeil's helpfulness.  You must pretend to pursue him back towards the GDI base.  They will open the perimeter to let him in.  Once he is in, he will deactivate the perimeter shortly thereafter.";
        case TXT_NOD12B: return "We suggest that the brotherhood should not suffer the indignations of the past.  In order to prevent history from repeating itself, you must steal the firing codes for GDI's ion cannon.    Paranoid security measures prevent GDI from storing the entire code in one place.  Therefore, use a chameleon spy to infiltrate three different comm centers.  Once we have the codes and the spy is safely evacuated, we will be able to use GDI's ion cannon against them in the final assault.  Unfortunately GDI will have to use the ion cannon once before we can use the codes.";
        case TXT_JANUARY: return "January";
        case TXT_FEBRUARY: return "February";
        case TXT_MARCH: return "March";
        case TXT_APRIL: return "April";
        case TXT_MAY: return "May";
        case TXT_JUNE: return "June";
        case TXT_JULY: return "July";
        case TXT_AUGUST: return "August";
        case TXT_SEPTEMBER: return "September";
        case TXT_OCTOBER: return "October";
        case TXT_NOVEMBER: return "November";
        case TXT_DECEMBER: return "December";
        case TXT_RELEASE_THE_HOUNDS: return "Release";
        case TXT_LOADING_GAME1A: return "Analyzing combat zone topography...";
        case TXT_LOADING_GAME1C: return "Compiling wartime conventions...";
        case TXT_LOADING_GAME1D: return "Gathering intel on involved factions...";
        case TXT_LOADING_GAME1E: return "Creating theories on likely enemy plan...";
        case TXT_LOADING_GAME1F: return "Secondary check of combat zone...";
        case TXT_LOADING_GAME1G: return "Deploying forces to combat zone...";
        case TXT_LOADING_GAME1H: return "Final analysis of outcome...";
        case TXT_RECONNECT_HELP1: return "Click on a name to propose removing that player from the game.";
        case TXT_RECONNECT_HELP2: return "If all other players have connection times in the red then you have probably been";
        case TXT_RECONNECT_HELP3: return "Check your connection to the internet.  If you were disconnected from the internet";
        case TXT_RECONNECT_HELP4: return "disconnected from the network.";
        case TXT_RECONNECT_HELP5: return "Click cancel to abort this game and return to the lobby.";
        case TXT_RECONNECT_HELP2B: return "disconnected from your internet service provider.";
        case TXT_RECONNECT_HELP3B: return "you can re-dial your provider and continue the game as normal provided the other";
        case TXT_RECONNECT_HELP3C: return "players don't elect to remove you from the game..";
        case TXT_RECONNECT_KICK_SELF: return "You can't propose removing yourself. Click cancel to leave the game.";
        case TXT_RECONNECT_KICK_RECEIVED: return "%s proposes kicking %s from the game.";
        case TXT_BIOME_TUNDRA: return "Tundra";
        case TXT_BIOME_TAIGA: return "Taiga";
        case TXT_BIOME_TEMPERATE: return "Temperate";
        case TXT_BIOME_DESERT: return "Desert";
        case TXT_TIME_MORNING: return "Morning";
        case TXT_TIME_AFTERNOON: return "Afternoon";
        case TXT_TIME_DUSK: return "Dusk";
        case TXT_TIME_NIGHT: return "Night";
        case TXT_MAPSIZE_SMALL: return "Small";
        case TXT_MAPSIZE_MEDIUM: return "Medium";
        case TXT_MAPSIZE_LARGE: return "Large";
        case TXT_MAPSIZE_VERY_LARGE: return "V.Large";
        case TXT_RANDOM_MAP_DESCRIPTION: return "Random Map";
        case TXT_LOADING_GAME1B: return "Compensating for ambient light values...";
        case TXT_CONSENT_REQUIRED: return "Since you are under the age of 13 our privacy policy requires that you send us a parental consent form to continue.  Press 'yes' to open your web browser to this page.";
        case TXT_CLAN_NOSTART: return "To start a BattleClan tournament game there needs to be an even number of people from two clans.  Everyone in the game must be in a clan.";
        case TXT_DISABLED: return "Your account has been temporarily disabled.  Make sure the Email address you registered with is correct.  Would you like to open your web browser to get more information?";
        case TXT_SERIALBANNED: return "(NOT USED ANYMORE)";
        case TXT_SERIALDUP: return "Your Serial number is currently in use.  Would you like to open your web browser to get more information?";
        case TXT_NOD04B: return "Taking out this weak GDI position will allow us to reclaim our Sarajevo temple without interruption.  Move in under the cover of an ion storm when GDI's communications will be down.  Take out the comm center before the storm subsides.";
        case TXT_SEL_USER: return "You must select a user to kick/ignore/ban them.";
        case TXT_GOLD: return "Gold";
        case TXT_ORANGE: return "Orange";
        case TXT_SKY_BLUE: return "Sky Blue";
        case TXT_PINK: return "Pink";
        case TXT_COLOR_IN_USE: return "The requested color is already taken.";
        case TXT_NO_CLAN: return "You must be in a BattleClan to join this game.";
        case TXT_LANGCODE: return "0";
        case TXT_SERIAL_DUP: return "There are already 2 players with your serial# in that game.";
        case TXT_MISMATCH: return "Game versions incompatible. To make sure you have the latest version, visit www.westwood.com";
        case TXT_NO_EXPANSION_SCENARIO: return "Error - other player does not have this expansion scenario.";
        case TXT_SCENARIO_ERROR: return "Incompatable scenario file detected. The scenario may be corrupt.";
        case TXT_INVALID: return "Invalid option switch.";
        case TXT_OPTION_HELP_01: return "Tiberian Sun © 1999, Westwood Studios\n";
        case TXT_OPTION_HELP_02: return "Parameters:\n";
        case TXT_OPTION_HELP_03: return "  -DESTNET = Specify Network Number of destination system\n";
        case TXT_OPTION_HELP_04: return "  -SOCKET = Network Socket ID (0 - 16383)\n";
        case TXT_OPTION_HELP_05: return "  -STEALTH = Hide multiplayer names (\"Boss mode\")\n";
        case TXT_OPTION_HELP_06: return "  -MESSAGES = Allow messages from outside this game.\n";
        case TXT_MAP_ERROR: return "Map Error!";
        case TXT_SCATTER: return "Scatter";
        case TXT_SCATTER_DESC: return "Scatter selected object(s).";
        case TXT_CENTER_VIEW: return "Center View";
        case TXT_CENTER_VIEW_DESC: return "Center the view about selected object(s).";
        case TXT_CENTER_BASE: return "Center Base";
        case TXT_LINE_BUSY: return "Line busy.";
        case TXT_NUMBER_INVALID: return "Number invalid.";
        case TXT_DIALING: return "Dialing...";
        case TXT_DIALING_CANCELED: return "Dialing Canceled";
        case TXT_WAITING_FOR_CALL: return "Waiting for Call...";
        case TXT_ANSWERING_CANCELED: return "Answering Canceled";
        case TXT_SYSTEM_NOT_RESPONDING: return "Other system not responding!";
        case TXT_NO_COMP_ENABLE_RESPONSE: return "Error - Modem failed to respond to compression enable command. Your Windows configuration may be incorect.";
        case TXT_NO_EC_ENABLE_RESPONSE: return "Error - Modem failed to respond to error correction enable command. Your Windows configuration may be incorrect.";
        case TXT_CREATE_TEAM_DESC: return "Creates Team %d from currently selected units.";
        case TXT_SELECT_TEAM: return "Select Team %2d";
        case TXT_SELECT_TEAM_DESC: return "Select members of team %d.";
        case TXT_ADD_SELECT_TEAM: return "Add Select Team %2d";
        case TXT_ADD_SELECT_TEAM_DESC: return "Select members of team %d without unselecting other units.";
        case TXT_CENTER_TEAM: return "Center Team %2d";
        case TXT_CENTER_TEAM_DESC: return "Select and center view about team %d.";
        case TXT_NEXT_OBJECT: return "Next Object";
        case TXT_NEXT_OBJECT_DESC: return "Select the next object.";
        case TXT_PREV_OBJECT: return "Previous Object";
        case TXT_PREV_OBJECT_DESC: return "Select the previous object.";
        case TXT_STOP_OBJECT: return "Stop Object";
        case TXT_STOP_OBJECT_DESC: return "Stop the selected object(s).";
        case TXT_GUARD: return "Guard";
        case TXT_GUARD_DESC: return "Set the selected object(s) into 'guard area' mode.";
        case TXT_VICTORIOUS: return "You Are Victorious!";
        case TXT_CENTER_BASE_DESC: return "Center the view about the player's base.";
        case TXT_ALLIANCE: return "Alliance";
        case TXT_ALLIANCE_DESC: return "Toggle alliance with owner of selected object.";
        case TXT_SELECT_VIEW: return "Select View";
        case TXT_SELECT_VIEW_DESC: return "Select all owned objects in the current view.";
        case TXT_REPAIR_MODE: return "Repair Mode";
        case TXT_REPAIR_MODE_DESC: return "Toggle repair mode on / off.";
        case TXT_SELL_MODE: return "Sell Mode";
        case TXT_SELL_MODE_DESC: return "Toggle sell mode on / off.";
        case TXT_POWER_MODE: return "Power Mode";
        case TXT_POWER_MODE_DESC: return "Toggle power mode on / off.";
        case TXT_RADAR_EVENT: return "Goto Radar Event";
        case TXT_RADAR_EVENT_DESC: return "Center the tactical view on the last radar event.";
        case TXT_RADAR_TOGGLE: return "Radar Toggle";
        case TXT_RADAR_TOGGLE_DESC: return "Toggle radar display mode on / off.";
        case TXT_SIDEBAR_UP: return "Sidebar Up";
        case TXT_SIDEBAR_UP_DESC: return "Scrolls sidebar selection list upward.";
        case TXT_LSIDEBAR_UP: return "Structure List up";
        case TXT_LSIDEBAR_UP_DESC: return "Scroll sidebar structure selection list upward.";
        case TXT_RSIDEBAR_UP: return "Unit List Up";
        case TXT_RSIDEBAR_UP_DESC: return "Scroll sidebar unit selection list upward.";
        case TXT_SIDEBAR_PGUP: return "Sidebar PageUp";
        case TXT_SIDEBAR_PGUP_DESC: return "Page sidebar selection list upward.";
        case TXT_LSIDEBAR_PGUP: return "Structure List PageUp";
        case TXT_LSIDEBAR_PGUP_DESC: return "Page sidebar structure selection list upward.";
        case TXT_RSIDEBAR_PGUP: return "Unit List PageUp";
        case TXT_RSIDEBAR_PGUP_DESC: return "Page sidebar unit selection list upward.";
        case TXT_SIDEBAR_DOWN: return "Sidebar Down";
        case TXT_SIDEBAR_DOWN_DESC: return "Scroll sidebar selection list downward.";
        case TXT_LSIDEBAR_DOWN: return "Structure List Down";
        case TXT_LSIDEBAR_DOWN_DESC: return "Scroll sidebar structure selection list downward.";
        case TXT_RSIDEBAR_DOWN: return "Unit List Down";
        case TXT_RSIDEBAR_DOWN_DESC: return "Scroll sidebar unit selection list downward.";
        case TXT_SIDEBAR_PGDN: return "Sidebar PageDown";
        case TXT_SIDEBAR_PGDN_DESC: return "Page sidebar selection list downward.";
        case TXT_LSIDEBAR_PGDN: return "Structure List PageDown";
        case TXT_LSIDEBAR_PGDN_DESC: return "Page sidebar structure selection list downward.";
        case TXT_RSIDEBAR_PGDN: return "Unit List PageDown";
        case TXT_RSIDEBAR_PGDN_DESC: return "Page sidebar unit selection list downward.";
        case TXT_OPTIONS: return "Options Menu";
        case TXT_OPTIONS_DESC: return "Display game options dialog.";
        case TXT_SCROLL_N: return "Scroll North";
        case TXT_SCROLL_N_DESC: return "Scroll tactical map to the north.";
        case TXT_SCROLL_S: return "Scroll South";
        case TXT_SCROLL_S_DESC: return "Scroll tactical map to the south.";
        case TXT_SCROLL_E: return "Scroll East";
        case TXT_SCROLL_E_DESC: return "Scroll tactical map to the east.";
        case TXT_SCROLL_W: return "Scroll West";
        case TXT_SCROLL_W_DESC: return "Scroll tactical map to the west.";
        case TXT_VIEW_BOOKMARK1: return "View Bookmark 1";
        case TXT_VIEW_BOOKMARK1_DESC: return "View bookmarked map position 1.";
        case TXT_VIEW_BOOKMARK2: return "View Bookmark 2";
        case TXT_VIEW_BOOKMARK2_DESC: return "View bookmarked map position 2.";
        case TXT_VIEW_BOOKMARK3: return "View Bookmark 3";
        case TXT_VIEW_BOOKMARK3_DESC: return "View bookmarked map position 3.";
        case TXT_VIEW_BOOKMARK4: return "View Bookmark 4";
        case TXT_VIEW_BOOKMARK4_DESC: return "View bookmarked map position 4.";
        case TXT_SET_BOOKMARK1: return "Set Bookmark 1";
        case TXT_SET_BOOKMARK1_DESC: return "Set view bookmark map position 1.";
        case TXT_SET_BOOKMARK2: return "Set Bookmark 2";
        case TXT_SET_BOOKMARK2_DESC: return "Set view bookmark map position 2.";
        case TXT_SET_BOOKMARK3: return "Set Bookmark 3";
        case TXT_SET_BOOKMARK3_DESC: return "Set view bookmark map position 3.";
        case TXT_SET_BOOKMARK4: return "Set Bookmark 4";
        case TXT_SET_BOOKMARK4_DESC: return "Set view bookmark map position 4.";
        case TXT_FOLLOW: return "Follow";
        case TXT_FOLLOW_DESC: return "Toggle follow state of selected object(s).";
        case TXT_DEL_WAYPOINT: return "Delete Waypoint";
        case TXT_DEL_WAYPOINT_DESC: return "Delete selected waypoint.";
        case TXT_PAGEUSER: return "Page User";
        case TXT_PAGEUSER_DESC: return "Page a Westwood Online user. (Internet play only)";
        case TXT_SCENARIO_TOO_SMALL: return "This map has a %d player max.  The max includes human and AI players.";
        case TXT_DOWNLOAD_FAILED: return "The download failed, please check your connection and try again later.";
        case TXT_GAME_RESTART: return "Tiberian Sun will now restart to update itself.";
        case TXT_PASSWORD_TOO_SHORT: return "Your password must be exactly 8 letters long.";
        case TXT_PASSWORD_VERIFY: return "You need to enter the same password twice.";
        case TXT_LOB_1: return "GDI Barracks";
        case TXT_LOB_2: return "NOD Barracks";
        case TXT_LOB_3: return "GDI Comm. Center";
        case TXT_LOB_4: return "Temple of NOD";
        case TXT_LOB_5: return "GDI Tech Center";
        case TXT_LOB_6: return "Hand of NOD";
        case TXT_NEW_GAME: return "New Game";
        case TXT_NEW_CHAT: return "New Chat";
        case TXT_NEW: return "New";
        case TXT_GAME_CHAN: return "Tiberian Sun game channels";
        case TXT_OTHER_GAME: return "Other game channels";
        case TXT_OFFICIAL_CHAT: return "Official chat channels";
        case TXT_USER_CHAT: return "User chat channels";
        case TXT_GAME_PASSWORD: return "Game has a password";
        case TXT_LEAVE: return "Leave";
        case TXT_JOIN: return "Join";
        case TXT_OPER: return "Channel Operator";
        case TXT_VOICE: return "Voice";
        case TXT_IGNOREUSER: return "Ignore User";
        case TXT_ACCEPTED: return "Accepted";
        case TXT_JOINED_S: return "You joined channel %s";
        case TXT_REQUIRED_FIELD: return "A required field is missing, or invalid.";
        case TXT_SCENARIO_COLON: return "Scenario:";
        case TXT_TOURNEY_COLON: return "Tournament:";
        case TXT_BATTLE_CLAN: return "BattleClan";
        case TXT_HOST_RANK: return "Host Rank:";
        case TXT_UNRANKED: return "Unranked";
        case TXT_CANT_KICK: return "You cannot kick a player from a tournament game.";
        case TXT_HOST_CHANGED_OPTIONS: return "The host has changed game options, press accept if you're ready.";
        case TXT_GDI: return "GDI";
        case TXT_NOD: return "Nod";
        case TXT_GAME_ID: return "Game# %d";
        case TXT_TOURNAMENT_GAME: return "Tournament Game";
        case TXT_BATTLECLAN_GAME: return "BattleClan Game";
        case TXT_GAME: return "Game: %d";
        case TXT_WDT_FORMAT_TWO_LINES: return "%s\n%s";
        case TXT_WDT_TERRITORY_CONTROL: return "\nGDI: %2d%%\nNod: %2d%%";
        case TXT_WDT_REVIEWING_HISTORY: return "Reviewing History\n";
        case TXT_WDT_DAY: return "Day : %d";
        case TXT_BIOME_MUTATED: return "Mutated";
        case TXT_WDT_INVALID_MISSING: return "Invalid/Missing";
        case TXT_WDT_INFO_CORRUPT: return "The World Domination Tour information was either not downloaded or is corrupt.";
        case TXT_WDT_NAME_DESC_RANK: return "%s\n%s\nRank : %d";
        case TXT_WDT_CANCEL: return "Cancel";
        case TXT_WDT_WEB_PAGE: return "Web Page";
        case TXT_WDT_NAME_RANK: return "%s\nRank : %d";
        case TXT_BAD_MAP_01: return "The host has selected";
        case TXT_BAD_MAP_02: return "a modified map.";
        case TXT_BAD_MAP_03: return "This may give the host";
        case TXT_BAD_MAP_04: return "an unfair advantage.";
        case TXT_BAD_MAP_05: return "No preview available.";
        case TXT_AMOUNT_VERY_FEW: return "Very Few";
        case TXT_AMOUNT_FEW: return "Few";
        case TXT_AMOUNT_MANY: return "Many";
        case TXT_AMOUNT_VERY_MANY: return "Very Many";
        case TXT_AMOUNT_VERY_LOW: return "Very Low";
        case TXT_AMOUNT_LOW: return "Low";
        case TXT_AMOUNT_HIGH: return "High";
        case TXT_AMOUNT_VERY_HIGH: return "Very High";
        case TXT_AMOUNT_VERY_SCARCE: return "Very Scarce";
        case TXT_AMOUNT_SCARCE: return "Scarce";
        case TXT_AMOUNT_ABUNDANT: return "Abundant";
        case TXT_AMOUNT_VERY_ABUNDANT: return "Very Abundant";
        case TXT_AMOUNT_VERY_SPARSE: return "Very Sparse";
        case TXT_AMOUNT_SPARSE: return "Sparse";
        case TXT_AMOUNT_HEAVY: return "Heavy";
        case TXT_AMOUNT_VERY_HEAVY: return "Very Heavy";
        case TXT_WDT_HARV_TRUCE: return "Harvester Truce";
        case TXT_WDT_BASES_ON: return "Starting Bases";
        case TXT_WDT_BASES_OFF: return "No Starting Bases";
        case TXT_WDT_MCV_REDEPLOY_ON: return "Redeployable MCV";
        case TXT_WDT_FOG_OF_WAR: return "Fog of War";
        case TXT_WDT_BRIDGE_DESTROY_ON: return "Bridges Destroyable";
        case TXT_WDT_BRIDGE_DESTROY_OFF: return "Indestructable Bridges";
        case TXT_WDT_GOODIES_ON: return "Goodie Crates";
        case TXT_WDT_GOODIES_OFF: return "No Goodie Crates";
        case TXT_WDT_TIME_OF_DAY_TRANSITIONS: return "Time of Day Transitions";
        case TXT_WDT_FMT_CLIFFS: return "%s Cliffs";
        case TXT_WDT_FMT_ACCESSIBILITY: return "%s Accessibility";
        case TXT_WDT_FMT_HILLS: return "%s Hills";
        case TXT_WDT_FMT_TIBERIUM: return "%s Tiberium";
        case TXT_WDT_FMT_TIBERIUM_FIELDS: return "%s Tiberium Fields";
        case TXT_WDT_FMT_WATER: return "%s Water";
        case TXT_WDT_FMT_VEGETATION: return "%s Vegetation";
        case TXT_WDT_FMT_CITIES: return "%s Cities";
        case TXT_WDT_LIFEFORMS: return "Tiberium Lifeforms";
        case TXT_WDT_VEINHOLES: return "Veinholes";
        case TXT_WDT_TECHLEVEL: return "Tech Level %d";
        case TXT_WDT_STARTING_UNITS: return "%d Starting Units";
        case TXT_WDT_CREDITS: return "%d Credits";
        case TXT_WDT_MCV_REDEPLOY_OFF: return "MCV Not Redeployable";
        case TXT_WDT_SHORT_GAME_ON: return "Short Game";
        case TXT_WDT_SHORT_GAME_OFF: return "Unlimited Game Length";
        case TXT_WDT_TWO_PLAYER_ONLY: return "Two Player Only";
        case TXT_WDT_FOUR_PLAYER_ONLY: return "Four Player Only";
        case TXT_WDT_MAP_TINY: return "Tiny Map";
        case TXT_WDT_MAP_SMALL: return "Small Map";
        case TXT_WDT_MAP_NARROW: return "Narrow Map";
        case TXT_WDT_MAP_TALL_NARROW: return "Tall & Narrow Map";
        case TXT_WDT_MAP_SHORT: return "Short Map";
        case TXT_WDT_MAP_LARGE: return "Large Map";
        case TXT_WDT_MAP_SHORT_WIDE: return "Short & Wide Map";
        case TXT_WDT_MAP_HUGE: return "Huge Map";
        case TXT_FETCHING_SQUAD: return "Fetching squad information";
        case TXT_FETCHING_LADDER: return "Fetching ladder information";
        case TXT_WDT_NET_ERR: return "Could not connect to the World Domination Tour server, or there is no server available";
        case TXT_NO_FREE_SLOTS: return "There are no more free slots in that game for your side";
        case TXT_WDT_FRONT_LINE_CHANGED: return "The active World Domination Tour territories have changed.  Relocating to new front line...";
        case TXT_FETCHING_WDT: return "Fetching World Domination Tour information";
        case TXT_CHOOSE_MAP: return "Please Choose Map";
        case TXT_WOL_LOGGING_OUT: return "Logging off Westwood Online";
        case TXT_PLAYER_CHANGED_LATENCY: return "Player %s has changed the connection speed setting.";
        case TXT_PLAYER_CHANGED_SPEED: return "Player %s has changed the game speed setting.";
        case TXT_WORST_CONNECTION: return "Bad";
        case TXT_POOR_CONNECTION: return "Poor";
        case TXT_GOOD_CONNECTION: return "Normal";
        case TXT_BEST_CONNECTION: return "Fast";
        case TXT_WARNING_LOCALE_UNKNOWN: return "You have not set your location. Click OK to continue anyway or cancel to go back and set your location.";
        case TXT_DELETE_USER: return "Are you sure you want to remove user '%s' from the login list?";
        case TXT_ALL_LOCATIONS: return "All Locations";
        case TXT_TS_PLAYERS: return "Tiberian Sun Players";
        case TXT_TS_BATTLECLANS: return "Tiberian Sun BattleClans";
        case TXT_FS_PLAYERS: return "Firestorm Players";
        case TXT_FS_BATTLECLANS: return "Firestorm BattleClans";
        case TXT_WDT_NOD_PLAYERS: return "WDT Nod Players";
        case TXT_WDT_GDI_PLAYERS: return "WDT GDI Players";
        case TXT_SELECT_TYPE: return "Select Same Type";
        case TXT_SELECT_TYPE_DESC: return "Selects all on-screen units of the same types as currently selected. Press twice quickly to select across the whole map.";
        case TXT_FIRESTORM_REQUIRED: return "Firestorm required to join this game.";
        case TXT_FIRESTORM_MUST_ENABLE: return "Firestorm must be enabled to join this game.";
        case TXT_FIRESTORM_NO_JOIN_TS: return "Unable to join original Tiberian Sun game with Firestorm enabled.";
        case TXT_SERIALUNKNOWN: return "Your serial number was not found.  This is most likely due to a mistyped serial number during installation.  You must reinstall the game, specifying a valid serial number, to play online.";
        case TXT_SKUSERIALMISMATCH: return "Your serial number is associated with a product other than Tiberian Sun.  You must reinstall the game, specifying a valid Tiberian Sun serial number, to play online.";
        case TXT_WDT_TIBERIUM_RANGE: return "Very Scarce Tiberium";
        case TXT_WDT_TIBERIUM_SCARCE: return "Scarce Tiberium";
        case TXT_WDT_TIBERIUM_ABUNDANT: return "Abundant Tiberium";
        case TXT_WDT_TIBERIUM_VERY_ABUNDANT: return "Very Abundant Tiberium";
        case TXT_WDT_TIBERIUM_FIELDS_RANGE: return "Very Few Tiberium Fields";
        case TXT_WDT_TIBERIUM_FIELDS_FEW: return "Few Tiberium Fields";
        case TXT_WDT_TIBERIUM_FIELDS_MANY: return "Many Tiberium Fields";
        case TXT_WDT_TIBERIUM_FIELDS_NUMEROUS: return "Numerous Tiberium Fields";
        case TXT_WDT_ACCESSIBILITY_RANGE: return "Very Low Accessibility";
        case TXT_WDT_ACCESSIBILITY_LOW: return "Low Accessibility";
        case TXT_WDT_ACCESSIBILITY_HIGH: return "High Accessibility";
        case TXT_WDT_ACCESSIBILITY_VERY_HIGH: return "Very High Accessibility";
        case TXT_WDT_CLIFFS_RANGE: return "Very Few Cliffs";
        case TXT_WDT_CLIFFS_FEW: return "Few Cliffs";
        case TXT_WDT_CLIFFS_MANY: return "Many Cliffs";
        case TXT_WDT_CLIFFS_NUMEROUS: return "Numerous Cliffs";
        case TXT_WDT_HILLS_RANGE: return "Very Few Hills";
        case TXT_WDT_HILLS_FEW: return "Few Hills";
        case TXT_WDT_HILLS_MANY: return "Many Hills";
        case TXT_WDT_HILLS_NUMEROUS: return "Numerous Hills";
        case TXT_WDT_WATER_RANGE: return "Very Scarce Water";
        case TXT_WDT_WATER_SCARCE: return "Scarce Water";
        case TXT_WDT_WATER_ABUNDANT: return "Abundant Water";
        case TXT_WDT_WATER_VERY_ABUNDANT: return "Very Abundant Water";
        case TXT_WDT_VEGETATION_RANGE: return "Very Sparse Vegetation";
        case TXT_WDT_VEGETATION_SPARSE: return "Sparse Vegetation";
        case TXT_WDT_VEGETATION_HEAVY: return "Heavy Vegetation";
        case TXT_WDT_VEGETATION_VERY_HEAVY: return "Very Heavy Vegetation";
        case TXT_WDT_CITIES_RANGE: return "Very Few Cities";
        case TXT_WDT_CITIES_FEW: return "Few Cities";
        case TXT_WDT_CITIES_MANY: return "Many Cities";
        case TXT_WDT_CITIES_NUMEROUS: return "Numerous Cities";
        case TXT_MULTI_ENGINEERS: return "Multi-Engineers";
        case TXT_NORMAL_ENGINEERS: return "Normal Engineers";
        case TXT_NEED_PLAYERS_TO_START: return "You need %d players to start the game.";
        case TXT_NEED_EQUAL_TEAMS: return "You must have an equal number of GDI and Nod players to start the game.";
        case TXT_WDT_NO_ALLIANCE_CHANGE: return "You cannot change alliances in a World Domination Tour game.";
        case TXT_UNKNOWN_STATUS: return "Unknown Status";
        case TXT_UNKNOWN_PING: return "Unknown Ping";
        case TXT_MANUAL_PLACE: return "Place Building";
        case TXT_MANUAL_PLACE_DESC: return "Enters placement mode for the completed building waiting on the sidebar.";
        case TXT_TO_TEAM: return "To Team:";
        case TXT_TO_OBSERVERS: return "To Observers:";
        case TXT_CHAT_TAGGED: return "%s [%s]";
        case TXT_CHAT_TO_TEAM: return "to team";
        case TXT_CHAT_TO_OBSERVERS: return "to observers";
        case TXT_CHAT_TO_PLAYER: return "to %s";
        case TXT_CHAT: return "Chat";
        case TXT_CHAT_TO_ALL: return "Message to All";
        case TXT_CHAT_TO_ALL_DESC: return "Starts a message to every player.";
        case TXT_CHAT_TO_ALLIES: return "Message to Team";
        case TXT_CHAT_TO_ALLIES_DESC: return "Starts a message to your allies, or to the other observers while you watch.";
        case TXT_AUTOSAVING: return "Auto-saving...";
        case TXT_AUTOSAVE_FAILED: return "The game could not be auto-saved.";
        case TXT_AUTOSAVE_DESCRIPTION: return "Auto-Save %d: %s";
        case TXT_AUTOSAVE_MULTIPLAYER: return "Multiplayer Game (Auto-Save)";
        case TXT_SAVE_FAILED: return "The game could not be saved.";
        case TXT_REPEAT_LAST_BUILDING: return "Repeat Last Building";
        case TXT_REPEAT_LAST_BUILDING_DESC: return "Queues the last structure that was built, while it is still on the sidebar.";
        case TXT_REPEAT_LAST_INFANTRY: return "Repeat Last Infantry";
        case TXT_REPEAT_LAST_INFANTRY_DESC: return "Queues the last infantry that was trained, while it is still on the sidebar.";
        case TXT_REPEAT_LAST_UNIT: return "Repeat Last Vehicle";
        case TXT_REPEAT_LAST_UNIT_DESC: return "Queues the last vehicle that was built, while it is still on the sidebar.";
        case TXT_REPEAT_LAST_AIRCRAFT: return "Repeat Last Aircraft";
        case TXT_REPEAT_LAST_AIRCRAFT_DESC: return "Queues the last aircraft that was built, while it is still on the sidebar.";
        case TXT_SCROLL_NE: return "Scroll North-East";
        case TXT_SCROLL_NE_DESC: return "Scroll tactical map to the north-east.";
        case TXT_SCROLL_SE: return "Scroll South-East";
        case TXT_SCROLL_SE_DESC: return "Scroll tactical map to the south-east.";
        case TXT_SCROLL_SW: return "Scroll South-West";
        case TXT_SCROLL_SW_DESC: return "Scroll tactical map to the south-west.";
        case TXT_SCROLL_NW: return "Scroll North-West";
        case TXT_SCROLL_NW_DESC: return "Scroll tactical map to the north-west.";
        case TXT_JUMP_CAMERA_W: return "Jump Camera West";
        case TXT_JUMP_CAMERA_W_DESC: return "Jump tactical map to the west edge of the map.";
        case TXT_JUMP_CAMERA_E: return "Jump Camera East";
        case TXT_JUMP_CAMERA_E_DESC: return "Jump tactical map to the east edge of the map.";
        case TXT_JUMP_CAMERA_N: return "Jump Camera North";
        case TXT_JUMP_CAMERA_N_DESC: return "Jump tactical map to the north edge of the map.";
        case TXT_JUMP_CAMERA_S: return "Jump Camera South";
        case TXT_JUMP_CAMERA_S_DESC: return "Jump tactical map to the south edge of the map.";
        case TXT_PREV_THEME: return "Music: Previous Track";
        case TXT_PREV_THEME_DESC: return "Plays the previous music track.";
        case TXT_NEXT_THEME: return "Music: Next Track";
        case TXT_NEXT_THEME_DESC: return "Plays the next music track.";
        case TXT_NOW_PLAYING: return "Now Playing: %s";
        case TXT_VETERANCY_FILTER: return "Veterancy Filter";
        case TXT_VETERANCY_FILTER_DESC: return "Narrows a mixed selection to its highest rank, and cycles through the ranks when pressed again.";
        case TXT_VETERANCY_FILTER_ADD: return "Veterancy Filter (Add Lower)";
        case TXT_VETERANCY_FILTER_ADD_DESC: return "Adds the next lower rank back to a filtered selection.";
        case TXT_HEALTH_FILTER: return "Health Filter";
        case TXT_HEALTH_FILTER_DESC: return "Narrows a mixed selection to its most damaged units, and cycles through the health bands when pressed again.";
        case TXT_HEALTH_FILTER_ADD: return "Health Filter (Add Lower)";
        case TXT_HEALTH_FILTER_ADD_DESC: return "Adds the next healthier band back to a filtered selection.";
        case TXT_SELECT_ONE_LESS: return "Select One Less";
        case TXT_SELECT_ONE_LESS_DESC: return "Removes the last unit from the selection.";
        case TXT_QUICK_SAVE: return "Quick Save";
        case TXT_QUICK_SAVE_DESC: return "Saves the game to the quick save file.";
        case TXT_QUICK_LOAD: return "Quick Load";
        case TXT_QUICK_LOAD_DESC: return "Loads the quick save file.";
        case TXT_QUICKSAVE_DESCRIPTION: return "Quick Save: %s";
        case TXT_NO_QUICKSAVE: return "No quick save to load.";
        case TXT_MOVIE_SKIP_ONE: return "%s wants to skip the video.";
        case TXT_MOVIE_SKIP_SELF: return "You want to skip the video.";
        case TXT_MOVIE_SKIP_MANY: return "%d players want to skip the video.";
        case TXT_MOVIE_SKIP_AGREE: return "Press ESC to agree. (%d/%d)";
        case TXT_MOVIE_SKIP_WAIT: return "Waiting for other players... (%d/%d)";
        case TXT_SYNC_STATUS_OUT: return "Desynced";
        case TXT_SYNC_STATUS_LEFT: return "Quit";
        case TXT_LOADING_IN_SECONDS: return "Loading in %d seconds...";
        case TXT_LOADING_IN_SECOND: return "Loading in 1 second...";
        case TXT_LOADING_SAVED_GAME: return "Loading the saved game...";
        case TXT_CHAT_HINT: return "Type here to chat...";
        case TXT_DIFFICULTY_LEVEL: return "Difficulty: %s";
        case TXT_ADD_TO_TEAM: return "Add To Team %2d";
        case TXT_ADD_TO_TEAM_DESC: return "Adds the selected units to team %d and selects the whole team.";
        case TXT_GAME_SAVED: return "Game saved.";
        case TXT_GAME_AUTO_SAVED: return "Game auto-saved.";
        case TXT_SCENARIO_DATA_DAMAGED: return "Unable to read scenario %s: its map data is damaged.";
        case TXT_CONNECTION_QUALITY_STATUS: return "Connection quality target: %s.";
        case TXT_CONNECTION_QUALITY_RUNG: return "%s (rung %u)";
        default: return "";
    }
}
#endif
